### PR TITLE
Fix bug in UDP socket failing with WSAECONNRESET in the read thread

### LINKED ISSUE #2924: Airsim crashes if you run px4 and close airsim before 2 seconds.
Reproducing steps:
* Run PX4
* Run and exit AirSim before 2 seconds passes

Errors (and fixes):
MavLinkMultirotorApi.hpp
image
Then after fixing this error with the commented out line you get this:
image
The error is actually at the connect part. This naturally happens as mav_vehicle = nullptr after disconnecting, so using the commented out lines fixes this too.

### LINKED ISSUE #3698: AirSim crashes as soon as it connects to PX4
### What's your question?
AirSim crashes when I run it right after I initialize PX4. I am not sure what may cause this issue as I am new to AirSim.

### Include context on what you are trying to achieve
I want to create some MAVSDK based code. So, I decided to use PX4 in SITL mode with AirSim as the simulator. I first downloaded the pre-compiled binary with Blocks environment. Everything works fine when I run the Blocks.sh without changing settings.json file in the Documents/AirSim/ folder. I was able to run both car and quadcopter model without any issues. Then I followed all the steps provided in https://microsoft.github.io/AirSim/px4_sitl/ to install and setup PX4 to work with AirSim. However, AirSim crashes as soon as I get the log `INFO  [simulator] Simulator connected on TCP port 4560.` on PX4. The complete AirSim logs for both the cases are provided below.

**AirSim log without changing settings.json**
[logAirSim.txt](https://github.com/microsoft/AirSim/files/6489418/logAirSim.txt)

**AirSim log with changed settings.json**
[logAirSimPx4.txt](https://github.com/microsoft/AirSim/files/6489428/logAirSimPx4.txt)
I also get following message in terminal
```
terminating with uncaught exception of type std::runtime_error: UdpClientPort socket send failed with error: 9

Signal 6 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
Malloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Malloc Size=131160 LargeMemoryPoolOffset=459112 
Malloc Size=81006 LargeMemoryPoolOffset=540142 
Aborted (core dumped)
```

#### Context details
**OS**: Ubuntu 20.04
**AirSim**: Blocks v1.4.0
**PX4**:  v1.11.3
**settings.json**:
```
{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor",
    "ClockType": "SteppableClock",
    "Vehicles": {
        "PX4": {
            "VehicleType": "PX4Multirotor",
            "UseSerial": false,
            "LockStep": true,
            "UseTcp": true,
            "TcpPort": 4560,
            "ControlPortLocal": 14540,
            "ControlPortRemote": 14580,
            "Sensors":{
                "Barometer":{
                    "SensorType": 1,
                    "Enabled": true,
                    "PressureFactorSigma": 0.0001825
                }
            },
            "Parameters": {
                "NAV_RCL_ACT": 0,
                "NAV_DLL_ACT": 0,
                "COM_OBL_ACT": 1,
                "LPE_LAT": 47.641468,
                "LPE_LON": -122.140165
            }
        }
    }
}
```

### Include details of what you already did to find answers
I also tried running PX4 with jMAVSim and it works fine. So, it seems that the issue is with AirSim. However, I don't know much about unreal engine and so I would prefer not to look at the source code of AirSim.

### PR DESCRIPTION
**Pull request by lovettchris**
Fixes: #3698    
Fixes: #2924

## About
Fix bug in UDP socket failing with WSAECONNRESET in the read thread if it tries to read to soon.  The fix is to put a retry count in the UdpClientPort where it automatically reconnects up to 10 times.  Also fixed a null ref crash on mav_vehicle_ that happens in some cases like if you kill px4 process while drone is flying.

## How Has This Been Tested?
Windows with PX4 in WSL2 and in WSL1 with latest PX4 master bits as of today (1.12.0)

## Screenshots (if appropriate):

### CODE REVIEW

File: MavLinkCom/src/serial_com/UdpClientPort.cpp [hunk 1]
```diff
@@ -152,25 +162,47 @@ class UdpClientPort::UdpSocketImpl
         return 0;
     }
 
+    int reconnect()
+    {
+        // try and reconnect
+        std::string localHost = inet_ntoa(localaddr.sin_addr);
+        std::string remoteHost = remoteAddress();
+        int remotePort = ntohs(remoteaddr.sin_port);
+        int localPort = 0;
```
Comment (zimmy87) [inline MavLinkCom/src/serial_com/UdpClientPort.cpp:171]: locals should be under_scored

File: PythonClient/multirotor/opencv_show.py [hunk 2]
```diff
@@ -27,28 +27,28 @@ def printUsage():
...
 
 print (cameraTypeMap[cameraType])
 
 client = airsim.MultirotorClient()
-client.confirmConnection()
-client.enableApiControl(True)
-client.armDisarm(True)
-client.takeoffAsync().join()
+
+print("Connected: now whiled this script is running, you can open another")
```
Comment (zimmy87) [inline PythonClient/multirotor/opencv_show.py:38]: "whiled" should be "while"

**Review by zimmy87 — CHANGES_REQUESTED** [review]
Just a few typos. I did some regression testing with connecting to PX4 & running the hello_drone.py, box.py, and a custom script sending the drone in a zig-zag pattern. Didn't notice any regressions with this testing.

Also tested each of the linked issues with and without this PR applied and found the following:
| issue | w/o PR applied                                  | w/ PR applied                                   |
|-------|-------------------------------------------------|-------------------------------------------------|
| #3698 | repros (AirSim hang on quit after PX4 shutdown) | repros (AirSim hang on quit after PX4 shutdown) |
| #2924 | no repro (w/ PX4 on both WSL2 & cygwin)         | no repro                                        |
| #2112 | repros                                          | no repro                                        |
| #634  | repros (dupe of #2112)                          | no repro (dupe of #2112)                        |
| #1516 | no repro                                        | no repro                                        |

During testing, I encountered a delay in the PX4 connection process where the console outputs `not receiving any messages from HIL, please restart your HIL node and try again`:

Screenshot from 2021-06-16 09-55-27

This issue didn't persist for me and went away after restarting my system, so I can't confirm whether it's due to this PR or not, but I wanted to bring it up here in case you had some insight.

File: PythonClient/multirotor/opencv_show.py (hunk 2 above)
Comment (lovettchris) [reply PythonClient/multirotor/opencv_show.py]: Fixed

File: MavLinkCom/src/serial_com/UdpClientPort.cpp (hunk 1 above)
Comment (lovettchris) [reply MavLinkCom/src/serial_com/UdpClientPort.cpp]: fixed

**Review by zimmy87 — APPROVED** [review]

**Comment by zimmy87** [comment]
Thanks for the contribution @lovettchris! Going ahead with merge
