### PR TITLE
Sets bCapture* true only while showing subwindow 

### LINKED ISSUE #1724: Segmentation Image API bug when in headless mode of NoDisplay setting
I found that in the latest master branch, the `simGetImages` API returns wrong image types if we use `"NoDisplay"` viewmode in `settings.json`. I use the Blocks environment and the following python scripts to reproduce this bug. When the viewmode is `"NoDisplay"`, the following code gets the RGB image instead of the segmentation image.

```python
import numpy as np
import cv2
import airsim

def uncompressed_to_cvimage(response):
    '''
    Convert uncompressed RGBA image to cv2 BGR format H x W x Channels
    '''
    assert response.pixels_as_float == False
    img1d = np.fromstring(response.image_data_uint8, dtype=np.uint8)
    img = img1d.reshape(response.height, response.width, 4)[:, :, 0:-1]
    return img[:, :, ::-1]

client = airsim.MultirotorClient()
client.confirmConnection()
client.enableApiControl(True)
client.armDisarm(True)

response = client.simGetImages([airsim.ImageRequest(
    "0", airsim.ImageType.Segmentation, False, False)])[0]
seg = uncompressed_to_cvimage(response)
cv2.imshow('seg', seg)
cv2.waitKey(0)
```

### LINKED ISSUE #2967: Cannot obtain Depth Images under NoDisplay mode
# Cannot obtain Depth Images under NoDisplay mode
Under the **NoDisplay** mode, **depth image** cannot be correctly obtained.
The code we use to get depth image is given here:
```
    // ROS_WARN_STREAM("event should happen " << (event.current_real - event.current_expected).toSec());
    try
    {
        ROS_INFO("try request imgs");
        std::vector<ImageRequest> request = { ImageRequest("0", ImageType::Scene, false, false), ImageRequest("0", ImageType::DepthPlanner, true, false) };
        const vector<ImageResponse>& response =  image_client_.simGetImages(request);
        pubImgsFromResponse(response);
    }
...      
        ImageResponse scene_img = response[0];
        ImageResponse depth_img = response[1];

        scene_img_publisher_.publish(getSceneImgFromResponce(scene_img, curr_ros_time, "scene_image"));
        depth_img_publisher_.publish(getDepthImgFromResponce(depth_img, curr_ros_time, "depth_image"));
```
With this code, the image obtained is the same as the 'Scene' image except that it is in gray scale. (As demenstrated below).

When returning to "**fly with me**" mode, the above code works well, obtaining the right images. 

Does anyone know how to fix this problem?

### LINKED ISSUE #3070: low image fps while using simGetImage python API
I am trying to apply image processing techniques on image stream received from simGetImage API. I want an image stream of 30 fps. But the image stream I get from simGetImage gives an fps of 10-12. The simulation fps (50 fps) is good when simGetImage API is not used. 

My code (ROS wrapper):

    self.image_publisher_rate = 0.01
    rospy.Timer(rospy.Duration(self.image_publisher_rate), self.image_publisher_cb)

    def image_publisher_cb(self, timer):
        image_data = self.get_camera_data()
        self.image_pub.publish(self.bridge.cv2_to_imgmsg(image_data, encoding='bgr8'))

    def get_camera_data(self):
        rawImage = self.image_client.simGetImage(self.camera_name, airsim.ImageType.Scene)
    
        if rawImage is not None:
            frame = cv2.imdecode(airsim.string_to_uint8_array(rawImage), cv2.IMREAD_UNCHANGED)
            return frame
        
OS : Ubuntu 18.04
Game Engine : Unity 2020.1.4f1

Other answers I saw were mostly related to projects depending on Unreal Engine (as opposed to mine)

I want my camera fps to be equal to or more than 30 fps. How do I achieve this?

### LINKED ISSUE #3504: Segmentation Image bug when running headless
## Bug report 
- AirSim Version/#commit: 1.4
- UE/Unity version: 4.25
- autopilot version:
- OS Version: tested on Ubuntu 18.04 and MacOS

### What's the issue you encountered?
This issue is a duplicate of #1724, but since it seems like it hasn't been resolved I want to know if anyone has found a solution. The problem happens when trying to grab segmentation images using the PythonClient API while running airsim in headless mode (ViewMode: "NoDisplay"). When doing this the returned image is a kind of color-distorted rgb image of the entire scene. No segmentations at all. I am using the simGetImages() for grabbing segmentation images.

This is what i want (recorded with ViewMode: Fpv):
Skærmbillede 2021-03-22 kl  16 53 48

This is what i get (recorded with ViewMode: NoDisplay):
Skærmbillede 2021-03-22 kl  16 53 12

I hope someone can point me in the right direction for a fix. Thank you in advance!

### LINKED ISSUE #4112: FPS stays low after stopping a recording
## Bug report 

- AirSim Version/#commit: 1.6.0
- UE/Unity version: 4.27
- autopilot version: N/A
- OS Version: Windows 10 21H1

### What's the issue you encountered?

After stopping a recording via the red button, the simulation's FPS stays as low as it was during the recording, instead of going back up to the value prior to starting a recording.

### Settings

{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",

  "StereoCameraBaseline": 0.24,

  "Recording": 
  {
    "RecordOnMove": false,
    "RecordInterval": 30,
    "Folder": "C:\\Users\\Max\\Documents\\AirSim\\Recordings",
    "Enabled": false,
    "Cameras": [
      {
        "CameraName": "front_left",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "VehicleName": "SimpleFlight",
        "Compress": true
      },
      {
        "CameraName": "front_left",
        "ImageType": 1,
        "PixelsAsFloat": true,
        "VehicleName": "SimpleFlight",
        "Compress": true
      },
      {
        "CameraName": "front_left",
        "ImageType": 5,
        "PixelsAsFloat": false,
        "VehicleName": "SimpleFlight",
        "Compress": true
      },
      {
        "CameraName": "front_right",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "VehicleName": "SimpleFlight",
        "Compress": true
      }
    ]
  },

  "CameraDefaults": 
  {
    "CaptureSettings": 
	  [
		  {
			  "ImageType": 0,
			  "Width": 256,
			  "Height": 144,
			  "FOV_Degrees": 90,
			  "ProjectionMode": ""
		  },
		  {
			  "ImageType": 1,
			  "Width": 256,
			  "Height": 144,
			  "FOV_Degrees": 90,
			  "ProjectionMode": ""
		  },
		  {
			  "ImageType": 5,
			  "Width": 256,
			  "Height": 144,
			  "FOV_Degrees": 90,
			  "ProjectionMode": ""
		  }
    ]
  }
}
### How can the issue be reproduced?

1. Start a recording with a demand high enough to cut down the FPS
2. Stop the recording

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**
Totally agree with this statement, but I spent a day trying to fix it with no luck. I'm completely stumped :(

### PR DESCRIPTION
**Pull request by nznaza**
Sets bAlwaysPersistRenderingState to true. This fixes bugs related to capture while on NoDisplay.
Sets bCaptureOnMovement and bCaptureEveryFrame to true only when they are going to be viewed on a subwindow

Fixes: #1724 
Fixes: #2967
Fixes: #3504
Fixes: #3070

Partially fixes #4112

Should fix most of the FPS while capturing problems.

## About

This PR fixes the NoDisplay/Headless bug by setting bAlwaysPersistRenderingState to true.

Setting bCaptureOnMovement and bCaptureEveryFrame to true only while it's on an active subwindow camera improves the performance of image capture/recording and python simGetImages

## How Has This Been Tested?

A python script was used to display the captured images to corroborate the accurate capture of the desired captures; the same script was used for all captures using ComputerVision.

```
import airsim
from cv2 import data
import numpy as np
from airsim import *
import cv2 
import datetime

def ImageResponsetoImage(selected):
    isFloat = selected.pixels_as_float
    if isFloat:
        img1d = np.array(selected.image_data_float)
    else:
        img1d = np.frombuffer(selected.image_data_uint8, dtype=np.uint8)

    width = selected.width
    height = selected.height
    channels = int(img1d.size / (height * width))
    img = img1d.reshape(height, width, channels)
    if (isFloat):
        depthinmm = img*1000
        depth_16bit =  np.clip(depthinmm, 0,65535) 
        return depth_16bit.astype(np.uint16)

    else:
        return img.astype(np.uint8)

if __name__ == "__main__":
    client = MultirotorClient()
    client.confirmConnection()

    i = 0
    inc = True
    while True:
        responses = client.simGetImages(
            [
                ImageRequest("front_left", ImageType.Scene, False, False),
                ImageRequest("front_left", ImageType.DepthPerspective, True, False),
                ImageRequest("front_left", ImageType.Segmentation, False, False),
                
                ImageRequest("front_center", ImageType.Scene, False, False),
                ImageRequest("front_center", ImageType.DepthPerspective, True, False),
                ImageRequest("front_center", ImageType.Segmentation, False, False),
                
                ImageRequest("front_right", ImageType.Scene, False, False),
                ImageRequest("front_right", ImageType.DepthPerspective, True, False),
                ImageRequest("front_right", ImageType.Segmentation, False, False),
                
                ImageRequest("bottom_center", ImageType.Scene, False, False),
                ImageRequest("bottom_center", ImageType.DepthPerspective, True, False),
                ImageRequest("bottom_center", ImageType.Segmentation, False, False),

                ImageRequest("back_center", ImageType.Scene, False, False),
                ImageRequest("back_center", ImageType.DepthPerspective, True, False),
                ImageRequest("back_center", ImageType.Segmentation, False, False),
                
            ]
        )
        tm = datetime.datetime.now().second % 10
        
        if tm % 2 == 0 :
            if inc:
                i += 1
            inc = False
        else:
            inc = True   
        if i >= len(responses):
            i = 0
        selected = responses[i]

        cv2.imshow("", ImageResponsetoImage(selected))
        cv2.waitKey(1)

```

Performance goes back up after stopping capture while on NoDisplay, but stays the same after recording or using the python simGetImages, but this can be fixed by displaying and hiding a subwindow.

settings.json

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "ViewMode": "NoDisplay",
  "SimMode": "ComputerVision",
  "Recording": {
    "RecordOnMove": true,
    "RecordInterval": 0.05,
    "Folder": "",
    "Enabled": false,
    "Cameras": [
        { "CameraName": "0", "ImageType": 0, "PixelsAsFloat": false,  "VehicleName": "ComputerVision", "Compress": true },
        { "CameraName": "0", "ImageType": 1, "PixelsAsFloat": false,  "VehicleName": "ComputerVision", "Compress": true },
        { "CameraName": "0", "ImageType": 2, "PixelsAsFloat": false,  "VehicleName": "ComputerVision", "Compress": true },
        { "CameraName": "0", "ImageType": 7, "PixelsAsFloat": false,  "VehicleName": "ComputerVision", "Compress": true }
    ]
  },
  "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 640,
        "Height": 480
      },
      {
        "ImageType": 2,
        "Width": 640,
        "Height": 480
      },
      {
        "ImageType": 7,
        "Width": 640,
        "Height": 480
      },
      {
        "ImageType": 8,
        "Width": 640,
        "Height": 480
      },
      {
        "ImageType": 9,
        "Width": 640,
        "Height": 480
      },
      {
        "ImageType": 5,
        "Width": 640,
        "Height": 480
      }
    ],
    "NoiseSettings": [
      {
        "Enabled": false,
        "ImageType": 7,

        "RandContrib": 0.2,
        "RandSpeed": 100000.0,
        "RandSize": 500.0,
        "RandDensity": 2,

        "HorzWaveContrib":0.03,
        "HorzWaveStrength": 0.08,
        "HorzWaveVertSize": 1.0,
        "HorzWaveScreenSize": 1.0,

        "HorzNoiseLinesContrib": 1.0,
        "HorzNoiseLinesDensityY": 0.01,
        "HorzNoiseLinesDensityXY": 0.5,

        "HorzDistortionContrib": 1.0,
        "HorzDistortionStrength": 0.002
      }
    ]
  },
  "SegmentationSettings": {
    "InitMethod": "",
    "MeshNamingMethod": "StaticMeshName",
    "OverrideExisting": true
  }
}

```

## Screenshots (if appropriate)

NoDisplay

RGB
Previous:
PreFixRGB

FixRGB

Depth:
Previous:
PreFixDepth

After:
FixDepth

Segmentation 
Previous:
PreFixSegmentation

After:
FixSegmentation

Performance captures

Recording previous to fix
Recording prefix

After recording and showing and hiding subwindow (small gain)
Recording preFix aSubwindows

Recording after fix (Lower timings, )
Recording after fix

After recording and showing and hiding subwindow (Back to normal)
Recording after Fix Subwindows

Python capture before fix
python capture before

Python capture post fix
python capture

Python capture before fix (Only front_center)
python before only front

Python capture after fix (Only front_center)
python after only front

Python capture before fix (Only front_center Scene)
only RGB

Python capture after fix (Only front_center Scene)
after only RGB

While capturing with python's simGetImages the performance after the fix are lower, but measurable: 205 ms vs 185ms, 70ms vs 54, single images are within margin error, but fix is still lower

For comparison here are the timings of all cameras and NoDIsplay

While capturing
capture python ND

After stopping capturing, the levels go back to normal without needing to enable a subwindow.
After capture python ND

### CODE REVIEW

File: Unreal/Plugins/AirSim/Source/CameraDirector.cpp [hunk 1]
```diff
@@ -344,21 +344,16 @@ void ACameraDirector::notifyViewModeChanged()
...
 
     UWorld* world = GetWorld();
     UGameViewportClient* gameViewport = world->GetGameViewport();
-    if (mode_ == ECameraDirectorMode::CAMERA_DIRECTOR_MODE_NODISPLAY) {
-        gameViewport->bDisableWorldRendering = 1;
-    }
-    else {
-        gameViewport->bDisableWorldRendering = 0;
-    }
+    gameViewport->bDisableWorldRendering = (uint32)mode_;
```
Comment (rajat2004) [inline Unreal/Plugins/AirSim/Source/CameraDirector.cpp:358]: You can just use the `nodisplay` variable instead of casting `mode_`

File: Unreal/Plugins/AirSim/Source/PIPCamera.cpp [hunk 2]
```diff
@@ -98,7 +98,7 @@ void APIPCamera::BeginPlay()
         render_targets_[image_type] = NewObject<UTextureRenderTarget2D>();
     }
 
-    onViewModeChanged(false);
+    onViewModeChanged(true);
```
Comment (rajat2004) [inline Unreal/Plugins/AirSim/Source/PIPCamera.cpp:101]: So in the beginning, we set all cameras to NoDisplay mode to improve performance?
 Would be great if you could add some comments in the code also as to why this helps

File: Unreal/Plugins/AirSim/Source/CameraDirector.cpp [hunk 3]
```diff
@@ -344,21 +344,16 @@ void ACameraDirector::notifyViewModeChanged()
...
-    if (front_camera_)
-        front_camera_->onViewModeChanged(nodisplay);
+    //if (fpv_camera_)
+    //    fpv_camera_->onViewModeChanged(nodisplay);
+    //if (backup_camera_)
+    //    backup_camera_->onViewModeChanged(nodisplay);
+    //if (ExternalCamera)
+    //    ExternalCamera->onViewModeChanged(nodisplay);
+    //if (front_camera_)
+    //    front_camera_->onViewModeChanged(nodisplay);
```
Comment (rajat2004) [inline Unreal/Plugins/AirSim/Source/CameraDirector.cpp:354]: Why are these no longer needed? And it's better to just remove the code rather then keep commented out pieces

**Review by rajat2004 — COMMENTED** [review]
Still need to test, but any idea why the performance for simGetImages dropped?

File: Unreal/Plugins/AirSim/Source/CameraDirector.cpp (hunk 1 above)
Comment (nznaza) [reply Unreal/Plugins/AirSim/Source/CameraDirector.cpp:358]: Correct, I was removing the branch assignation and used the wrong variable, will issue a commit to address this, thanks.

File: Unreal/Plugins/AirSim/Source/PIPCamera.cpp (hunk 2 above)
Comment (nznaza) [reply Unreal/Plugins/AirSim/Source/PIPCamera.cpp:101]: We initialize all cameras with bCaptureOnMovement and bCaptureEveryFrame to false.

This improves performance because the capture components are no longer updating every frame and only update while requesting an image (and are set to true while we are showing them on a sub-window because sub-window captures don’t count as a request)

File: Unreal/Plugins/AirSim/Source/CameraDirector.cpp (hunk 3 above)
Comment (nznaza) [reply Unreal/Plugins/AirSim/Source/CameraDirector.cpp:354]: Because cameras all cameras start with bCaptureOnMovement and bCaptureEveryFrame set to false regardless of nodisplay on BeginPlay(), and only required to be set true if there are going to be shown on a sub-window

I didn’t remove the code from commit while testing for regressions, but this is indeed no longer needed

**Comment by nznaza** [comment]
> Still need to test, but any idea why the performance for simGetImages dropped?

Sorry I don’t quite get the question, if you mean why is performance still drops while simGetImages is called: it’s because we still need to acquire the images (this is what causes the performance drop) this will commit will only drop while there is a request for the camera instead of having all of them updating every frame

**Comment by rajat2004** [comment]
Ah, I think I misunderstood the issue, I thought the FPS of `simGetImages` itself dropped, rather than the viewport. If possible, could you try the [image_benchmarker.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/computer_vision/image_benchmarker.py) script with and without your fix, just to get a sense of performance improvement?

**Comment by zimmy87** [comment]
Thanks for submitting this fix @nznaza! Tested this locally using the repro steps for #1724 and #2967. Confirmed #1724 and #3504 (which is a duplicate of #1724). Unfortunately, I was still able to repro #2967 and I didn't see any significant performance change using the [image_benchmarker.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/computer_vision/image_benchmarker.py) script, so I suspect #3070 still repros. Considering this does fix some of the issues, I'm gonna go ahead and merge this, we can address the other issues in a separate PR.
