### PR TITLE
fix ROS topic names

### LINKED ISSUE #2602: Run active SLAM system on Airsim
I'd like to run active ORB_SLAM2 system on Airsim, but I'm confused  how  Simple PID Position Controller Node works. I 've tried to launch this node but terminal showed "wait for odometry" even if I have launch airsim_node which provides it. 
It seems services provided by Simple PID Position Controller Node are able to control drones. I cannot understand the docs well, and I doubt whether I need to configure Mavros and PX4. 

Another question about Unreal4 scenes. I download block enviroment from [website](https://github.com/microsoft/AirSim/releases/tag/v1.2.0Linux) , but when exec the ORB_SLAM2, error occurs . When executes the enviroment on UE4, no error shows.

`ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Stereo

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded in 6.79s
Create new map.

Camera Parameters: 
- fx: 336
- fy: 336
- cx: 336
- cy: 188
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 20
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1200
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 4.99025
OMPL version: 1.4.2
[ERROR] [1587315470.619680566]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
[ERROR] [1587315470.746396180]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
[ERROR] [1587315470.880795029]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
[ERROR] [1587315471.003468894]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
[ERROR] [1587315471.110782676]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
[ERROR] [1587315471.220163417]: cv_bridge exception: Image is wrongly formed: height * step != size  or  376 * 2016 != 1010688
`

### LINKED ISSUE #3805: How to call ros service
## Question
How to call ros services the right way?

### Include context on what you are trying to achieve
I'm just trying to call ros services like `/airsim_node/gps_goal` or `/airsim_node/local_position_goal` but they return errors.

1- First I run my Unreal Blocks environment, press play button
2- launch `/airsim_node` after setting up the terminal
`source devel/setup.bash`
`export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`
`export WSL_HOST_IP=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')`
`roslaunch airsim_ros_pkgs airsim_node.launch output:=screen host:=$WSL_HOST_IP`

3- launch `/pid_position_node`
`roslaunch airsim_ros_pkgs position_controller_simple.launch`

4- calling the service with its arguments `rosservice call /airsim_node/gps_goal 5 10 15 1 drone_1` returns `success: False message: ''`

5- calling service `rosservice call /airsim_node/local_position_goal 10 15 20 2 drone_1` returns `ERROR: service [/airsim_node/gps_goal] responded with an error:` and the `/pid_position_node` will loop forever printing out `[PIDPositionController] Moving to goal.` but never moving the drone
image

6- calling `/airsim_node/takeoff 1` does move the drone but also return `success: Flase`

I'm I doing something wrong here? I'm I missing something? The documentations provide no more explanations on ros services.

#### Context details
OS: Windows10 with WSL2 running Ubuntu 18.04 and ROS Melodic 
AirSim: 1.5
Python: 3.6
Unreal: 4.26

settings.json:
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "ViewMode": "Fpv",
  "ClockSpeed": 1.0,
  "Vehicles": {
    "drone_1": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 0,
        "AllowAPIWhenDisconnected": false
      },
      "Sensors": {
        "Imu" : {
          "SensorType": 2,
          "Enabled": true
        },
	"Barometer":{
                "SensorType": 1,
                "Enabled": true,
                "PressureFactorSigma": 0.0001825
        },
	"Gps": {
        "SensorType": 3,
        "Enabled" : true,
        "EphTimeConstant": 0.9,
        "EpvTimeConstant": 0.9,
        "EphInitial": 25,
        "EpvInitial": 25,
        "EphFinal": 0.1,
        "EpvFinal": 0.1,
        "EphMin3d": 3,
        "EphMin2d": 4,
        "UpdateLatency": 0.2,
        "UpdateFrequency": 50,
        "StartupDelay": 1
    },
	"Magnetometer": {
        "SensorType": 4,
        "Enabled" : true,
        "NoiseSigma": 0.005,
        "ScaleFactor": 1,
        "NoiseBias": 0,
        "UpdateLatency": 0,
        "UpdateFrequency": 50,
        "StartupDelay": 0
    },
        "LidarCustom": {
          "SensorType": 6,
          "Enabled": true,
          "NumberOfChannels": 16,
          "PointsPerSecond": 10000,
          "X": 0,
          "Y": 0,
          "Z": -1,
          "DrawDebugPoints": true
        }
      },
      "Cameras": {
        "front_center_custom": {
          "CaptureSettings": [
            {
              "PublishToRos": 1,
              "ImageType": 0,
              "Width": 640,
              "Height": 480,
              "FOV_Degrees": 27,
              "DepthOfFieldFstop": 2.8,
              "DepthOfFieldFocalDistance": 200.0, 
              "DepthOfFieldFocalRegion": 200.0,
              "TargetGamma": 1.5
            }
          ],
          "X": 0.50, "Y": 0, "Z": 0.10,
          "Pitch": 0, "Roll": 0, "Yaw": 0
        },
        "front_left_custom": {
          "CaptureSettings": [
            {
              "PublishToRos": 1,
              "ImageType": 0,
              "Width": 672,
              "Height": 376,
              "FOV_Degrees": 90,
              "TargetGamma": 1.5
            }, 
            {
              "PublishToRos": 1,
              "ImageType": 1,
              "Width": 672,
              "Height": 376,
              "FOV_Degrees": 90,
              "TargetGamma": 1.5
            }
          ],
          "X": 0.50, "Y": -0.06, "Z": 0.10,
          "Pitch": 0.0, "Roll": 0.0, "Yaw": 0.0
        },
        "front_right_custom": {
          "CaptureSettings": [
            {
              "PublishToRos": 1,
              "ImageType": 0,
              "Width": 672,
              "Height": 376,
              "FOV_Degrees": 90,
              "TargetGamma": 1.5
            }
          ],
          "X": 0.50, "Y": 0.06, "Z": 0.10,
          "Pitch": 0.0, "Roll": 0.0, "Yaw": 0.0
        }
      },
      "X": 2, "Y": 0, "Z": 0,
      "Pitch": 0, "Roll": 0, "Yaw": 0
    }
  },
  "SubWindows": [
    {"WindowID": 0, "ImageType": 0, "CameraName": "front_left_custom", "Visible": false},
    {"WindowID": 1, "ImageType": 0, "CameraName": "front_center_custom", "Visible": false},
    {"WindowID": 2, "ImageType": 0, "CameraName": "front_right_custom", "Visible": false}
  ]
}

### Include details of what you already did to find answers
I tried with different ROS versions, Kinetic, Melodic and Noetic.
I tried with different arguments.

### PR DESCRIPTION
**Pull request by zimmy87**
Fixes: #3805    
Fixes: #2602
Fixes: #3878 

## About

This PR updates vel_cmd_world_frame and odom_local_ned topic names to include vehicle name so that communication between PIDPositionController and AirsimROSWrapper. The changes for updating the odom_local_ned topic comes from @leoborgnino's work on #2789

## How Has This Been Tested?

ROS node was built with changes applied and the repro steps in #3805 were followed

## Screenshots (if appropriate):

### CODE REVIEW

File: ros/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp [hunk 1]
```diff
@@ -54,12 +54,19 @@ void PIDPositionController::initialize_ros()
     // ROS params
     double update_control_every_n_sec;
     nh_private_.getParam("update_control_every_n_sec", update_control_every_n_sec);
+    
+    std::string vehicle_name;
+
+    while(vehicle_name == "") {
+        nh_private_.getParam("/vehicle_name", vehicle_name);
+        ROS_INFO_STREAM("Waiting vehicle name");
+    }
```
Comment (rajat2004) [inline ros/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp:63]: Is a loop needed here? Also, [getParam](http://docs.ros.org/en/melodic/api/roscpp/html/classros_1_1NodeHandle.html#afb8dbc451e3c0dbc14c67438d21c9f2b) returns a bool whether the param exists or not, that can also be used for error checking. If needed, the `listVehicles` API could also be used for this ig

Comment (leoborgnino) [reply ros/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp:63]: Yes, I think a better solution could be addressed, this works but I don't think that is the most elegant solution (I did it so I can ensure that hahaha). Two problems I can remember:

1. That nasty loop
2. Multiple vehicles (this only if we think in a future multi-vehicle implementation of pd position controller)

1. Can be addressed by creating a service with String[] msg with the name of the vehicles and then using ros::service::waitForService("/vehicle_name_srv", -1)) function. (maybe a timeout of 100 sec instead infinity). So we have a service that provides the name of vehicles. My start thought was that names are static so a rosparam could be the solution. The while waiting is because the rosparam is set in the settings.json parser.
2. I think pd position controller doesn't support multiple vehicles (am I right, no?) this could be addressed by other PR but with the solution in 1, it's possible because we can get all the names and create the publisher for each one. Then a few changes in the methods to support the multiple independent controllers.

**Comment by jonyMarino** [comment]
David. can you solve the conflict, please?

**Comment by jonyMarino** [comment]
Thanks David!
